### ISSUE TITLE
Serial might fail if 

### ISSUE THREAD

**Issue by carlosperate** [Bottersnike/Micro-Pi#2]
The SerialConsole init tries to configure the first port listed by PySerial, which is likely not related to the microbit itself, so best case scenario it will fail on launch if its on use or inaccessible, worse case scenario your are configuring and/or locking a port that might be used for something else.

This is the bit of code I referring to:

```python
self.baudrate = 115200
self.ports = list(list_ports.grep(''))
self.serialLocation = self.ports[0][0] if self.ports else None
self.serialConnection = None if not self.serialLocation else serial.serial_for_url(self.serialLocation)
if self.serialLocation is not None:
    self.serialConnection.baudrate = self.baudrate
```

Which in my specific case causes the following exception because of `serial.serial_for_url(self.serialLocation)`:

```
> sudo python -m micropi
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/zeroneo/projects/Micro-Pi/micropi/__main__.py", line 22, in <module>
    micropi.main()
  File "micropi/micropi.py", line 1591, in main
    main = MainWin()
  File "micropi/micropi.py", line 401, in __init__
    self.serialConsole = SerialConsole()
  File "micropi/micropi.py", line 1120, in __init__
    self.serialConnection = None if not self.serialLocation else serial.serial_for_url(self.serialLocation)
  File "/usr/lib/python2.7/dist-packages/serial/__init__.py", line 78, in serial_for_url
    instance.open()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 282, in open
    self._reconfigurePort()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 311, in _reconfigurePort
    raise SerialException("Could not configure port: %s" % msg)
serial.serialutil.SerialException: Could not configure port: (5, 'Input/output error')
```

**Comment by Bottersnike** [comment]
Okay, I'll add a connect button. I don't want to filter to the Micro:Bit as the idea of the serial console is that it can be used for anything. I'll hopefully have that by tomorrow evening.

**Comment by Bottersnike** [comment]
Okay, give it a try now (after updating your local copy)

**Comment by carlosperate** [comment]
Doesn't crash anymore, good work!

**Comment by Bottersnike** [comment]
Np. Closed.
